// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Account struct {
	ID            int32     `json:"id"`
	CoUserID      int32     `json:"co_user_id"`
	CoCategoryID  int32     `json:"co_category_id"`
	StTitle       string    `json:"st_title"`
	StType        string    `json:"st_type"`
	StDescription string    `json:"st_description"`
	VlValue       int32     `json:"vl_value"`
	DtDate        time.Time `json:"dt_date"`
	DtCreatedAt   time.Time `json:"dt_created_at"`
}

type Category struct {
	ID            int32     `json:"id"`
	CoUserID      int32     `json:"co_user_id"`
	StTitle       string    `json:"st_title"`
	StType        string    `json:"st_type"`
	StDescription string    `json:"st_description"`
	DtCreatedAt   time.Time `json:"dt_created_at"`
}

type User struct {
	ID          int32     `json:"id"`
	StUsername  string    `json:"st_username"`
	StPassword  string    `json:"st_password"`
	StEmail     string    `json:"st_email"`
	DtCreatedAt time.Time `json:"dt_created_at"`
}
