// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccount(ctx context.Context, id int32) error
	DeleteCategories(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]GetAccountsRow, error)
	GetAccountsByUserIdAndst_type(ctx context.Context, arg GetAccountsByUserIdAndst_typeParams) ([]GetAccountsByUserIdAndst_typeRow, error)
	GetAccountsByUserIdAndst_typeAndCategoryId(ctx context.Context, arg GetAccountsByUserIdAndst_typeAndCategoryIdParams) ([]GetAccountsByUserIdAndst_typeAndCategoryIdRow, error)
	GetAccountsByUserIdAndst_typeAndCategoryIdAndst_title(ctx context.Context, arg GetAccountsByUserIdAndst_typeAndCategoryIdAndst_titleParams) ([]GetAccountsByUserIdAndst_typeAndCategoryIdAndst_titleRow, error)
	GetAccountsByUserIdAndst_typeAndCategoryIdAndst_titleAndst_description(ctx context.Context, arg GetAccountsByUserIdAndst_typeAndCategoryIdAndst_titleAndst_descriptionParams) ([]GetAccountsByUserIdAndst_typeAndCategoryIdAndst_titleAndst_descriptionRow, error)
	GetAccountsByUserIdAndst_typeAnddt_date(ctx context.Context, arg GetAccountsByUserIdAndst_typeAnddt_dateParams) ([]GetAccountsByUserIdAndst_typeAnddt_dateRow, error)
	GetAccountsByUserIdAndst_typeAndst_description(ctx context.Context, arg GetAccountsByUserIdAndst_typeAndst_descriptionParams) ([]GetAccountsByUserIdAndst_typeAndst_descriptionRow, error)
	GetAccountsByUserIdAndst_typeAndst_title(ctx context.Context, arg GetAccountsByUserIdAndst_typeAndst_titleParams) ([]GetAccountsByUserIdAndst_typeAndst_titleRow, error)
	GetAccountsGraph(ctx context.Context, arg GetAccountsGraphParams) (int64, error)
	GetAccountsReports(ctx context.Context, arg GetAccountsReportsParams) (int64, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoriesByUserIdAndType(ctx context.Context, arg GetCategoriesByUserIdAndTypeParams) ([]Category, error)
	GetCategoriesByUserIdAndTypeAndDescription(ctx context.Context, arg GetCategoriesByUserIdAndTypeAndDescriptionParams) ([]Category, error)
	GetCategoriesByUserIdAndTypeAndTitle(ctx context.Context, arg GetCategoriesByUserIdAndTypeAndTitleParams) ([]Category, error)
	GetCategory(ctx context.Context, id int32) (Category, error)
	GetUser(ctx context.Context, stUsername string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
